name: cem-experiments
channels:
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - pyyaml
  - pip
  - pip:
    - firebase-admin
    - gym==0.21.0
    - griddly==1.2.35
    - psutil
    - pyglet
    - pygame
    - python-dotenv
    - ptitprince
