name: cem-experiments
channels:
  - defaults
dependencies:
  - python=3.9 # Because Griddly docs say there are problems with Python 3.8 and OpenAI.
  - matplotlib
  - pip
  - pip:
    - griddly
    - pyglet
    - pygame
